;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
x-presser-mode auto 
inhook 3 
x-stitch-number 61 
tuck - f30 3 
tuck - f28 3 
tuck - f26 3 
tuck - f24 3 
tuck - f22 3 
tuck - f20 3 
tuck - f18 3 
tuck - f16 3 
tuck - f14 3 
tuck - f12 3 
tuck - f10 3 
tuck - f8 3 
tuck - f6 3 
tuck - f4 3 
tuck - f2 3 
tuck + f1 3 
tuck + f3 3 
tuck + f5 3 
tuck + f7 3 
tuck + f9 3 
tuck + f11 3 
tuck + f13 3 
tuck + f15 3 
tuck + f17 3 
tuck + f19 3 
tuck + f21 3 
tuck + f23 3 
tuck + f25 3 
tuck + f27 3 
tuck + f29 3 
miss + f30 3 
releasehook 3 
x-stitch-number 63 
knit - f30 3 
knit - f29 3 
knit - f28 3 
knit - f27 3 
knit - f26 3 
knit - f25 3 
knit - f24 3 
knit - f23 3 
knit - f22 3 
knit - f21 3 
knit - f20 3 
knit - f19 3 
knit - f18 3 
knit - f17 3 
knit - f16 3 
knit - f15 3 
knit - f14 3 
knit - f13 3 
knit - f12 3 
knit - f11 3 
knit - f10 3 
knit - f9 3 
knit - f8 3 
knit - f7 3 
knit - f6 3 
knit - f5 3 
knit - f4 3 
knit - f3 3 
knit - f2 3 
knit - f1 3 
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
knit - f30 3 
knit - f29 3 
knit - f28 3 
knit - f27 3 
knit - f26 3 
knit - f25 3 
knit - f24 3 
knit - f23 3 
knit - f22 3 
knit - f21 3 
knit - f20 3 
knit - f19 3 
knit - f18 3 
knit - f17 3 
knit - f16 3 
knit - f15 3 
knit - f14 3 
knit - f13 3 
knit - f12 3 
knit - f11 3 
knit - f10 3 
knit - f9 3 
knit - f8 3 
knit - f7 3 
knit - f6 3 
knit - f5 3 
knit - f4 3 
knit - f3 3 
knit - f2 3 
knit - f1 3 
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
knit - f30 3 
knit - f29 3 
knit - f28 3 
knit - f27 3 
knit - f26 3 
knit - f25 3 
knit - f24 3 
knit - f23 3 
knit - f22 3 
knit - f21 3 
knit - f20 3 
knit - f19 3 
knit - f18 3 
knit - f17 3 
knit - f16 3 
knit - f15 3 
knit - f14 3 
knit - f13 3 
knit - f12 3 
knit - f11 3 
knit - f10 3 
knit - f9 3 
knit - f8 3 
knit - f7 3 
knit - f6 3 
knit - f5 3 
knit - f4 3 
knit - f3 3 
knit - f2 3 
knit - f1 3 
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
knit - f30 3 
knit - f29 3 
knit - f28 3 
knit - f27 3 
knit - f26 3 
knit - f25 3 
knit - f24 3 
knit - f23 3 
knit - f22 3 
knit - f21 3 
knit - f20 3 
knit - f19 3 
knit - f18 3 
knit - f17 3 
knit - f16 3 
knit - f15 3 
knit - f14 3 
knit - f13 3 
knit - f12 3 
knit - f11 3 
knit - f10 3 
knit - f9 3 
knit - f8 3 
knit - f7 3 
knit - f6 3 
knit - f5 3 
knit - f4 3 
knit - f3 3 
knit - f2 3 
knit - f1 3 
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
knit - f30 3 
knit - f29 3 
knit - f28 3 
knit - f27 3 
knit - f26 3 
knit - f25 3 
knit - f24 3 
knit - f23 3 
knit - f22 3 
knit - f21 3 
knit - f20 3 
knit - f19 3 
knit - f18 3 
knit - f17 3 
knit - f16 3 
knit - f15 3 
knit - f14 3 
knit - f13 3 
knit - f12 3 
knit - f11 3 
knit - f10 3 
knit - f9 3 
knit - f8 3 
knit - f7 3 
knit - f6 3 
knit - f5 3 
knit - f4 3 
knit - f3 3 
knit - f2 3 
knit - f1 3 
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
knit - f30 3 
knit - f29 3 
knit - f28 3 
knit - f27 3 
knit - f26 3 
knit - f25 3 
knit - f24 3 
knit - f23 3 
knit - f22 3 
knit - f21 3 
knit - f20 3 
knit - f19 3 
knit - f18 3 
knit - f17 3 
knit - f16 3 
knit - f15 3 
knit - f14 3 
knit - f13 3 
knit - f12 3 
knit - f11 3 
knit - f10 3 
knit - f9 3 
knit - f8 3 
knit - f7 3 
knit - f6 3 
knit - f5 3 
knit - f4 3 
knit - f3 3 
knit - f2 3 
knit - f1 3 
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
knit - f30 3 
knit - f29 3 
knit - f28 3 
knit - f27 3 
knit - f26 3 
knit - f25 3 
knit - f24 3 
knit - f23 3 
knit - f22 3 
knit - f21 3 
knit - f20 3 
knit - f19 3 
knit - f18 3 
knit - f17 3 
knit - f16 3 
knit - f15 3 
knit - f14 3 
knit - f13 3 
knit - f12 3 
knit - f11 3 
knit - f10 3 
knit - f9 3 
knit - f8 3 
knit - f7 3 
knit - f6 3 
knit - f5 3 
knit - f4 3 
knit - f3 3 
knit - f2 3 
knit - f1 3 
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
knit - f30 3 
knit - f29 3 
knit - f28 3 
knit - f27 3 
knit - f26 3 
knit - f25 3 
knit - f24 3 
knit - f23 3 
knit - f22 3 
knit - f21 3 
knit - f20 3 
knit - f19 3 
knit - f18 3 
knit - f17 3 
knit - f16 3 
knit - f15 3 
knit - f14 3 
knit - f13 3 
knit - f12 3 
knit - f11 3 
knit - f10 3 
knit - f9 3 
knit - f8 3 
knit - f7 3 
knit - f6 3 
knit - f5 3 
knit - f4 3 
knit - f3 3 
knit - f2 3 
knit - f1 3 
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
knit - f30 3 
knit - f29 3 
knit - f28 3 
knit - f27 3 
knit - f26 3 
knit - f25 3 
knit - f24 3 
knit - f23 3 
knit - f22 3 
knit - f21 3 
knit - f20 3 
knit - f19 3 
knit - f18 3 
knit - f17 3 
knit - f16 3 
knit - f15 3 
knit - f14 3 
knit - f13 3 
knit - f12 3 
knit - f11 3 
knit - f10 3 
knit - f9 3 
knit - f8 3 
knit - f7 3 
knit - f6 3 
knit - f5 3 
knit - f4 3 
knit - f3 3 
knit - f2 3 
knit - f1 3 
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
knit - f30 3 
knit - f29 3 
knit - f28 3 
knit - f27 3 
knit - f26 3 
knit - f25 3 
knit - f24 3 
knit - f23 3 
knit - f22 3 
knit - f21 3 
knit - f20 3 
knit - f19 3 
knit - f18 3 
knit - f17 3 
knit - f16 3 
knit - f15 3 
knit - f14 3 
knit - f13 3 
knit - f12 3 
knit - f11 3 
knit - f10 3 
knit - f9 3 
knit - f8 3 
knit - f7 3 
knit - f6 3 
knit - f5 3 
knit - f4 3 
knit - f3 3 
knit - f2 3 
knit - f1 3 
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
knit - f30 3 
knit - f29 3 
knit - f28 3 
knit - f27 3 
knit - f26 3 
knit - f25 3 
knit - f24 3 
knit - f23 3 
knit - f22 3 
knit - f21 3 
knit - f20 3 
knit - f19 3 
knit - f18 3 
knit - f17 3 
knit - f16 3 
knit - f15 3 
knit - f14 3 
knit - f13 3 
knit - f12 3 
knit - f11 3 
knit - f10 3 
knit - f9 3 
knit - f8 3 
knit - f7 3 
knit - f6 3 
knit - f5 3 
knit - f4 3 
knit - f3 3 
knit - f2 3 
knit - f1 3 
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
knit - f30 3 
knit - f29 3 
knit - f28 3 
knit - f27 3 
knit - f26 3 
knit - f25 3 
knit - f24 3 
knit - f23 3 
knit - f22 3 
knit - f21 3 
knit - f20 3 
knit - f19 3 
knit - f18 3 
knit - f17 3 
knit - f16 3 
knit - f15 3 
knit - f14 3 
knit - f13 3 
knit - f12 3 
knit - f11 3 
knit - f10 3 
knit - f9 3 
knit - f8 3 
knit - f7 3 
knit - f6 3 
knit - f5 3 
knit - f4 3 
knit - f3 3 
knit - f2 3 
knit - f1 3 
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
knit - f30 3 
knit - f29 3 
knit - f28 3 
knit - f27 3 
knit - f26 3 
knit - f25 3 
knit - f24 3 
knit - f23 3 
knit - f22 3 
knit - f21 3 
knit - f20 3 
knit - f19 3 
knit - f18 3 
knit - f17 3 
knit - f16 3 
knit - f15 3 
knit - f14 3 
knit - f13 3 
knit - f12 3 
knit - f11 3 
knit - f10 3 
knit - f9 3 
knit - f8 3 
knit - f7 3 
knit - f6 3 
knit - f5 3 
knit - f4 3 
knit - f3 3 
knit - f2 3 
knit - f1 3 
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
knit - f30 3 
knit - f29 3 
knit - f28 3 
knit - f27 3 
knit - f26 3 
knit - f25 3 
knit - f24 3 
knit - f23 3 
knit - f22 3 
knit - f21 3 
knit - f20 3 
knit - f19 3 
knit - f18 3 
knit - f17 3 
knit - f16 3 
knit - f15 3 
knit - f14 3 
knit - f13 3 
knit - f12 3 
knit - f11 3 
knit - f10 3 
knit - f9 3 
knit - f8 3 
knit - f7 3 
knit - f6 3 
knit - f5 3 
knit - f4 3 
knit - f3 3 
knit - f2 3 
knit - f1 3 
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
knit - f30 3 
knit - f29 3 
knit - f28 3 
knit - f27 3 
knit - f26 3 
knit - f25 3 
knit - f24 3 
knit - f23 3 
knit - f22 3 
knit - f21 3 
knit - f20 3 
knit - f19 3 
knit - f18 3 
knit - f17 3 
knit - f16 3 
knit - f15 3 
knit - f14 3 
knit - f13 3 
knit - f12 3 
knit - f11 3 
knit - f10 3 
knit - f9 3 
knit - f8 3 
knit - f7 3 
knit - f6 3 
knit - f5 3 
knit - f4 3 
knit - f3 3 
knit - f2 3 
knit - f1 3 
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
knit - f30 3 
knit - f29 3 
knit - f28 3 
knit - f27 3 
knit - f26 3 
knit - f25 3 
knit - f24 3 
knit - f23 3 
knit - f22 3 
knit - f21 3 
knit - f20 3 
knit - f19 3 
knit - f18 3 
knit - f17 3 
knit - f16 3 
knit - f15 3 
knit - f14 3 
knit - f13 3 
knit - f12 3 
knit - f11 3 
knit - f10 3 
knit - f9 3 
knit - f8 3 
knit - f7 3 
knit - f6 3 
knit - f5 3 
knit - f4 3 
knit - f3 3 
knit - f2 3 
knit - f1 3 
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
knit - f30 3 
knit - f29 3 
knit - f28 3 
knit - f27 3 
knit - f26 3 
knit - f25 3 
knit - f24 3 
knit - f23 3 
knit - f22 3 
knit - f21 3 
knit - f20 3 
knit - f19 3 
knit - f18 3 
knit - f17 3 
knit - f16 3 
knit - f15 3 
knit - f14 3 
knit - f13 3 
knit - f12 3 
knit - f11 3 
knit - f10 3 
knit - f9 3 
knit - f8 3 
knit - f7 3 
knit - f6 3 
knit - f5 3 
knit - f4 3 
knit - f3 3 
knit - f2 3 
knit - f1 3 
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
knit - f30 3 
knit - f29 3 
knit - f28 3 
knit - f27 3 
knit - f26 3 
knit - f25 3 
knit - f24 3 
knit - f23 3 
knit - f22 3 
knit - f21 3 
knit - f20 3 
knit - f19 3 
knit - f18 3 
knit - f17 3 
knit - f16 3 
knit - f15 3 
knit - f14 3 
knit - f13 3 
knit - f12 3 
knit - f11 3 
knit - f10 3 
knit - f9 3 
knit - f8 3 
knit - f7 3 
knit - f6 3 
knit - f5 3 
knit - f4 3 
knit - f3 3 
knit - f2 3 
knit - f1 3 
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
knit - f30 3 
knit - f29 3 
knit - f28 3 
knit - f27 3 
knit - f26 3 
knit - f25 3 
knit - f24 3 
knit - f23 3 
knit - f22 3 
knit - f21 3 
knit - f20 3 
knit - f19 3 
knit - f18 3 
knit - f17 3 
knit - f16 3 
knit - f15 3 
knit - f14 3 
knit - f13 3 
knit - f12 3 
knit - f11 3 
knit - f10 3 
knit - f9 3 
knit - f8 3 
knit - f7 3 
knit - f6 3 
knit - f5 3 
knit - f4 3 
knit - f3 3 
knit - f2 3 
knit - f1 3 
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
knit - f30 3 
knit - f29 3 
knit - f28 3 
knit - f27 3 
knit - f26 3 
knit - f25 3 
knit - f24 3 
knit - f23 3 
knit - f22 3 
knit - f21 3 
knit - f20 3 
knit - f19 3 
knit - f18 3 
knit - f17 3 
knit - f16 3 
knit - f15 3 
knit - f14 3 
knit - f13 3 
knit - f12 3 
knit - f11 3 
knit - f10 3 
knit - f9 3 
knit - f8 3 
knit - f7 3 
knit - f6 3 
knit - f5 3 
knit - f4 3 
knit - f3 3 
knit - f2 3 
knit - f1 3 
knit + f1 3 
knit + f2 3 
knit + f3 3 
knit + f4 3 
knit + f5 3 
knit + f6 3 
knit + f7 3 
knit + f8 3 
knit + f9 3 
knit + f10 3 
knit + f11 3 
knit + f12 3 
knit + f13 3 
knit + f14 3 
knit + f15 3 
knit + f16 3 
knit + f17 3 
knit + f18 3 
knit + f19 3 
knit + f20 3 
knit + f21 3 
knit + f22 3 
knit + f23 3 
knit + f24 3 
knit + f25 3 
knit + f26 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
knit - f30 3 
knit - f29 3 
knit - f28 3 
knit - f27 3 
knit - f26 3 
knit - f25 3 
knit - f24 3 
knit - f23 3 
knit - f22 3 
knit - f21 3 
knit - f20 3 
knit - f19 3 
knit - f18 3 
knit - f17 3 
knit - f16 3 
knit - f15 3 
knit - f14 3 
knit - f13 3 
knit - f12 3 
knit - f11 3 
knit - f10 3 
knit - f9 3 
knit - f8 3 
knit - f7 3 
knit - f6 3 
knit - f5 3 
knit - f4 3 
knit - f3 3 
knit - f2 3 
knit - f1 3 
xfer f1 b1 
rack 1.0 
xfer b1 f2 
rack 0.25 
knit + f2 3 
miss + f3 3 
rack 0.0 
xfer f2 b2 
rack 1.0 
xfer b2 f3 
rack 0.25 
tuck + b2 3 
knit + f3 3 
miss + f4 3 
rack 0.0 
xfer f3 b3 
rack 1.0 
xfer b3 f4 
rack 0.25 
knit + f4 3 
miss + f5 3 
rack 0.0 
xfer f4 b4 
rack 1.0 
xfer b4 f5 
rack 0.25 
tuck + b4 3 
knit + f5 3 
miss + f6 3 
rack 0.0 
xfer f5 b5 
rack 1.0 
xfer b5 f6 
rack 0.25 
knit + f6 3 
miss + f7 3 
rack 0.0 
xfer f6 b6 
rack 1.0 
xfer b6 f7 
rack 0.25 
tuck + b6 3 
knit + f7 3 
miss + f8 3 
rack 0.0 
xfer f7 b7 
rack 1.0 
xfer b7 f8 
rack 0.25 
knit + f8 3 
miss + f9 3 
rack 0.0 
xfer f8 b8 
rack 1.0 
xfer b8 f9 
rack 0.25 
tuck + b8 3 
knit + f9 3 
miss + f10 3 
rack 0.0 
xfer f9 b9 
rack 1.0 
xfer b9 f10 
rack 0.25 
knit + f10 3 
miss + f11 3 
rack 0.0 
xfer f10 b10 
rack 1.0 
xfer b10 f11 
rack 0.25 
tuck + b10 3 
knit + f11 3 
miss + f12 3 
rack 0.0 
xfer f11 b11 
rack 1.0 
xfer b11 f12 
rack 0.25 
knit + f12 3 
miss + f13 3 
rack 0.0 
xfer f12 b12 
rack 1.0 
xfer b12 f13 
rack 0.25 
tuck + b12 3 
knit + f13 3 
miss + f14 3 
rack 0.0 
xfer f13 b13 
rack 1.0 
xfer b13 f14 
rack 0.25 
knit + f14 3 
miss + f15 3 
rack 0.0 
xfer f14 b14 
rack 1.0 
xfer b14 f15 
rack 0.25 
tuck + b14 3 
knit + f15 3 
miss + f16 3 
rack 0.0 
xfer f15 b15 
rack 1.0 
xfer b15 f16 
rack 0.25 
knit + f16 3 
miss + f17 3 
rack 0.0 
xfer f16 b16 
rack 1.0 
xfer b16 f17 
rack 0.25 
tuck + b16 3 
knit + f17 3 
miss + f18 3 
rack 0.0 
xfer f17 b17 
rack 1.0 
xfer b17 f18 
rack 0.25 
knit + f18 3 
miss + f19 3 
rack 0.0 
xfer f18 b18 
rack 1.0 
xfer b18 f19 
rack 0.25 
tuck + b18 3 
knit + f19 3 
miss + f20 3 
rack 0.0 
xfer f19 b19 
rack 1.0 
xfer b19 f20 
rack 0.25 
knit + f20 3 
miss + f21 3 
rack 0.0 
xfer f20 b20 
rack 1.0 
xfer b20 f21 
rack 0.25 
tuck + b20 3 
knit + f21 3 
miss + f22 3 
rack 0.0 
xfer f21 b21 
rack 1.0 
xfer b21 f22 
rack 0.25 
knit + f22 3 
miss + f23 3 
rack 0.0 
xfer f22 b22 
rack 1.0 
xfer b22 f23 
rack 0.25 
tuck + b22 3 
knit + f23 3 
miss + f24 3 
rack 0.0 
xfer f23 b23 
rack 1.0 
xfer b23 f24 
rack 0.25 
knit + f24 3 
miss + f25 3 
rack 0.0 
xfer f24 b24 
rack 1.0 
xfer b24 f25 
rack 0.25 
tuck + b24 3 
knit + f25 3 
miss + f26 3 
rack 0.0 
xfer f25 b25 
rack 1.0 
xfer b25 f26 
rack 0.25 
knit + f26 3 
miss + f27 3 
rack 0.0 
xfer f26 b26 
rack 1.0 
xfer b26 f27 
rack 0.25 
tuck + b26 3 
knit + f27 3 
miss + f28 3 
rack 0.0 
xfer f27 b27 
rack 1.0 
xfer b27 f28 
rack 0.25 
knit + f28 3 
miss + f29 3 
rack 0.0 
xfer f28 b28 
rack 1.0 
xfer b28 f29 
rack 0.25 
tuck + b28 3 
knit + f29 3 
miss + f30 3 
rack 0.0 
xfer f29 b29 
rack 1.0 
xfer b29 f30 
rack 0.25 
knit + f30 3 
rack 0.0 
knit - f30 3 
knit + f30 3 
knit - f30 3 
knit + f29 3 
knit + f30 3 
knit - f30 3 
knit - f29 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
knit - f30 3 
knit - f29 3 
knit - f28 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
knit - f30 3 
knit - f29 3 
knit - f28 3 
knit - f27 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
knit - f30 3 
knit - f29 3 
knit - f28 3 
knit - f27 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
knit - f30 3 
knit - f29 3 
knit - f28 3 
knit - f27 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
knit - f30 3 
knit - f29 3 
knit - f28 3 
knit - f27 3 
knit + f27 3 
knit + f28 3 
knit + f29 3 
knit + f30 3 
outhook 3 
rack 0.25 
drop b1 
drop f1 
drop b2 
drop f2 
drop b3 
drop f3 
drop b4 
drop f4 
drop b5 
drop f5 
drop b6 
drop f6 
drop b7 
drop f7 
drop b8 
drop f8 
drop b9 
drop f9 
drop b10 
drop f10 
drop b11 
drop f11 
drop b12 
drop f12 
drop b13 
drop f13 
drop b14 
drop f14 
drop b15 
drop f15 
drop b16 
drop f16 
drop b17 
drop f17 
drop b18 
drop f18 
drop b19 
drop f19 
drop b20 
drop f20 
drop b21 
drop f21 
drop b22 
drop f22 
drop b23 
drop f23 
drop b24 
drop f24 
drop b25 
drop f25 
drop b26 
drop f26 
drop b27 
drop f27 
drop b28 
drop f28 
drop b29 
drop f29 
drop b30 
drop f30 
